# Simple workflow to run API tests using dotnet test

name: API Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build API project first
        run: dotnet build Video-Project-Suite.Api/Video-Project-Suite.Api.csproj --configuration Release --no-restore
      - name: Build test project
        run: dotnet build Video-Project-Suite.Tests/Video-Project-Suite.Tests.csproj --configuration Release --no-restore
      - name: Run tests
        run: dotnet test Video-Project-Suite.Tests/Video-Project-Suite.Tests.csproj --no-build --verbosity normal
